## Basic report on the processed bins

```{r include=F}
library(knitr)
library(Biostrings)
options(scipen=999)
pb_dat <- report_dat$pb_dat
attach(pb_dat)
```

### Arguments

```{r}
x <- pb_dat
x$pb_out <- NULL
x$seqs <- NULL
print(x)
```

### Compute metrics

```{r, include=FALSE}
metrics <- NULL
i <- 1
for (i in seq_along(pb_out)){
  print(i)
  input_size <- length(pb_out[[i]]$src) + length(pb_out[[i]]$out)
  output_size <- length(pb_out[[i]]$src)
  out <- pb_out[[i]]$out
  src <- pb_out[[i]]$src
  dmat <- pb_out[[i]]$dmat
  min_dist <- min(as.dist(dmat))
  in_max_dist <- max(pb_out[[i]]$dmat)
  out_dmat <- dmat[match(names(src), colnames(dmat)), 
                   match(names(src), colnames(dmat))]
  out_max_dist <- max(out_dmat)
  min_out_dist <- min(as.dist(out_dmat))
  if (is.null(pb_out[[i]]$alignment)){
    gaps <- NA
    pos_no_mismatch <- NA
    pos_mismatch <- NA
    total_mismatches <- NA
    non_acgt <- NA
  } else {
    conMat <- consensusMatrix(pb_out[[i]]$alignment)
    gaps <- sum(conMat[-(1:4),])
    mismatches <- apply(conMat, 2, sum) - apply(conMat, 2, max)
    pos_no_mismatch <- sum(mismatches==0)
    pos_mismatch <- sum(mismatches!=0)
    total_mismatches <- sum(mismatches)
    non_acgt <- sum(consensusMatrix(DNAStringSet(pb_out[[i]]$consensus[[1]]))[-(1:4),])
  }
  metrics <- rbind(metrics,
    data.frame(input_size = input_size,
               output_size = output_size,
               min_dist = min_dist,
               in_max_dist = in_max_dist,
               out_max_dist = out_max_dist,
               min_out_dist = min_out_dist,
               gaps = gaps,
               pos_no_mismatch = pos_no_mismatch,
               pos_mismatch = pos_mismatch,
               total_mismatches = total_mismatches,
               non_acgt))
}
```

### Effects of outlier removal

#### Before and after bin sizes

```{r}
hist(metrics$input_size)
hist(metrics$output_size)
plot(metrics$output_size ~ metrics$input_size)
abline(a=0, b=1)
```

##### Where are the small bins coming from?

```{r}
small_bins <- subset(metrics, output_size < 6)
plot(jitter(small_bins$output_size) ~ jitter(small_bins$input_size))
abline(a=0, b=1)
```

#### Before and after bin distances

```{r}
hist(metrics$in_max_dist)
hist(metrics$out_max_dist)
hist(metrics$min_out_dist)
hist(metrics$in_max_dist - metrics$out_max_dist)
```

### Alignment step

#### Number of gaps inserted

```{r}
hist(metrics$gaps)
kable(data.frame(num_gaps = as.numeric(names(table(metrics$gaps))),
                 num_alignments = as.numeric(table(metrics$gaps))))
```

#### Number positions with mismatches in the alignment

```{r}
hist(metrics$pos_no_mismatch)
hist(metrics$pos_mismatch)
```

#### Total number of mismatches

```{r}
hist(metrics$total_mismatches)
```

#### NON-ACGT characters in consensus

```{r}
hist(metrics$non_acgt)
kable(data.frame(num_non_acgt = as.numeric(names(table(metrics$non_acgt))),
                 num_con_seq = as.numeric(table(metrics$non_acgt))))
```
